@startuml
class Cell {
    + _startScalelDelay : float = 0.04f
    + _startScaleTime : float = 0.2f
    + _startMoveAnimationTime : float = 0.32f
    + _selectedMoveAnimationTime : float = 0.16f
    + _moveAnimationTime : float = 0.32f
    + IsStartTweenPlaying : bool <<get>>
    + IsStarMovePlaying : bool <<get>>
    + hasSelectedMoveFinished : bool <<get>>
    + hasMoveFinished : bool <<get>>
    + Init(color:Color, x:int, y:int, offsetX:float, offsetY:float, isLocked:bool) : void
    + AnimateStartPosition(offsetX:float, offsetY:float) : void
    + GameFinished() : void
    + SelectedMoveStart() : void
    + SelectedMoveEnd() : void
    + SelectedMove(offset:Vector2) : void
    + MoveEnd() : void
}
MonoBehaviour <|-- Cell
Cell --> "Color" Color
Cell --> "Position" Vector2Int
Cell --> "startAnimation" Tween
Cell --> "startMoveAnimation" Tween
Cell --> "selectedMoveAnimation" Tween
Cell --> "moveAnimation" Tween
@enduml
