@startuml
class GameplayManagerColorSort {
    + {static} Rows : int
    + {static} Cols : int
    + offsetX : float
    + offsetY : float
    + ClickedPlayButton() : void
    + ClickedBack(button:Button) : void
    + ClickedRestart(button:Button) : void
    + ClickedNextLevel(button:Button) : void
    + Animate(target:GameObject, onComplete:System.Action, duration:float) : void
}
MonoBehaviour <|-- GameplayManagerColorSort
GameplayManagerColorSort --> "Instance" GameplayManagerColorSort
@enduml
