@startuml
class LevelData {
    + LevelName : string
}
struct Edge {
}
class "List`1"<T> {
}
ScriptableObject <|-- LevelData
LevelData --> "Edges<Edge>" "List`1"
Edge --> "Points<Vector2Int>" "List`1"
Edge --> "StartPoint" Vector2Int
Edge --> "EndPoint" Vector2Int
@enduml
