@startuml

!define RECTANGLE class
!define LARGE_SIZE 4096
skinparam dpi 50

!include .\\Assets\Project\Scripts\AnimationDotWeen.puml
!include .\\Assets\Project\Scripts\DBManager.puml
!include .\\Assets\Project\Scripts\GameManager.puml
!include .\\Assets\Project\Scripts\MainMenuManager.puml
!include .\\Assets\Project\Scripts\SoundManager.puml
!include .\\Assets\Common\Scripts\ColorSortLevels\AllLevelsColorSort.puml
!include .\\Assets\Common\Scripts\ColorSortLevels\LevelColorSort.puml
!include .\\Assets\Common\Scripts\ConnectLevels\LevelData.puml
!include .\\Assets\Common\Scripts\ConnectLevels\LevelList.puml
!include .\\Assets\Common\Scripts\PipesLevels\AllLevelsPipes.puml
!include .\\Assets\Common\Scripts\PipesLevels\LevelDataPipe.puml
!include .\\Assets\Project\Scripts\Colorsort\Cell.puml
!include .\\Assets\Project\Scripts\Colorsort\GameplayManagerColorSort.puml
!include .\\Assets\Project\Scripts\Colorsort\LevelButtonColorsort.puml
!include .\\Assets\Project\Scripts\Connnect\GameplayManager.puml
!include .\\Assets\Project\Scripts\Connnect\LevelButton.puml
!include .\\Assets\Project\Scripts\Connnect\Node.puml
!include .\\Assets\Project\Scripts\Database\LeaderboardEntry.puml
!include .\\Assets\Project\Scripts\Database\LeaderboardResponse.puml
!include .\\Assets\Project\Scripts\Database\LoginResponse.puml
!include .\\Assets\Project\Scripts\Database\ResetResponse.puml
!include .\\Assets\Project\Scripts\Database\UpdateResponse.puml
!include .\\Assets\Project\Scripts\Dayily challange\DailyChallengeManager.puml
!include .\\Assets\Project\Scripts\Pipes\GameplayManagerPipes.puml
!include .\\Assets\Project\Scripts\Pipes\LevelButtonPipes.puml
!include .\\Assets\Project\Scripts\Pipes\Pipe.puml
!include .\\Assets\TextMesh Pro\Examples & Extras\Scripts\Benchmark01_UGUI.puml
!include .\\Assets\TextMesh Pro\Examples & Extras\Scripts\Benchmark02.puml
!include .\\Assets\TextMesh Pro\Examples & Extras\Scripts\Benchmark03.puml
!include .\\Assets\TextMesh Pro\Examples & Extras\Scripts\Benchmark04.puml
!include .\\Assets\TextMesh Pro\Examples & Extras\Scripts\CameraController.puml
!include .\\Assets\TextMesh Pro\Examples & Extras\Scripts\ChatController.puml
!include .\\Assets\TextMesh Pro\Examples & Extras\Scripts\DropdownSample.puml
!include .\\Assets\TextMesh Pro\Examples & Extras\Scripts\EnvMapAnimator.puml
!include .\\Assets\TextMesh Pro\Examples & Extras\Scripts\ObjectSpin.puml
!include .\\Assets\TextMesh Pro\Examples & Extras\Scripts\ShaderPropAnimator.puml
!include .\\Assets\TextMesh Pro\Examples & Extras\Scripts\SimpleScript.puml
!include .\\Assets\TextMesh Pro\Examples & Extras\Scripts\SkewTextExample.puml
!include .\\Assets\TextMesh Pro\Examples & Extras\Scripts\TeleType.puml
!include .\\Assets\TextMesh Pro\Examples & Extras\Scripts\TextConsoleSimulator.puml
!include .\\Assets\TextMesh Pro\Examples & Extras\Scripts\TextMeshProFloatingText.puml
!include .\\Assets\TextMesh Pro\Examples & Extras\Scripts\TextMeshSpawner.puml
!include .\\Assets\TextMesh Pro\Examples & Extras\Scripts\TMPro_InstructionOverlay.puml
!include .\\Assets\TextMesh Pro\Examples & Extras\Scripts\TMP_DigitValidator.puml
!include .\\Assets\TextMesh Pro\Examples & Extras\Scripts\TMP_ExampleScript_01.puml
!include .\\Assets\TextMesh Pro\Examples & Extras\Scripts\TMP_FrameRateCounter.puml
!include .\\Assets\TextMesh Pro\Examples & Extras\Scripts\TMP_PhoneNumberValidator.puml
!include .\\Assets\TextMesh Pro\Examples & Extras\Scripts\TMP_TextEventCheck.puml
!include .\\Assets\TextMesh Pro\Examples & Extras\Scripts\TMP_TextEventHandler.puml
!include .\\Assets\TextMesh Pro\Examples & Extras\Scripts\TMP_TextInfoDebugTool.puml
!include .\\Assets\TextMesh Pro\Examples & Extras\Scripts\TMP_TextSelector_A.puml
!include .\\Assets\TextMesh Pro\Examples & Extras\Scripts\TMP_TextSelector_B.puml
!include .\\Assets\TextMesh Pro\Examples & Extras\Scripts\TMP_UiFrameRateCounter.puml
!include .\\Assets\TextMesh Pro\Examples & Extras\Scripts\VertexColorCycler.puml
!include .\\Assets\TextMesh Pro\Examples & Extras\Scripts\VertexJitter.puml
!include .\\Assets\TextMesh Pro\Examples & Extras\Scripts\VertexShakeA.puml
!include .\\Assets\TextMesh Pro\Examples & Extras\Scripts\VertexShakeB.puml
!include .\\Assets\TextMesh Pro\Examples & Extras\Scripts\VertexZoom.puml
!include .\\Assets\TextMesh Pro\Examples & Extras\Scripts\WarpTextExample.puml

@enduml
